name: Testing

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.5

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Testing
        uses: robherley/go-test-action@v0.1.0
        with:
          testArguments: ./...